/**
 * Emoji 数据列表
 * 支持中文关键词搜索，点击选择
 */

export interface EmojiItem {
  emoji: string;
  name: string;
  keywords?: string[];
}

export const EMOJI_LIST: EmojiItem[] = [
  // 🍎 食物水果
  { emoji: '🍎', name: '苹果', keywords: ['红', '水果', 'apple'] },
  { emoji: '🍌', name: '香蕉', keywords: ['黄', '水果', 'banana'] },
  { emoji: '🍊', name: '橙子', keywords: ['橘子', '水果', 'orange'] },
  { emoji: '🍋', name: '柠檬', keywords: ['酸', '水果', 'lemon'] },
  { emoji: '🍇', name: '葡萄', keywords: ['紫', '水果', 'grape'] },
  { emoji: '🍉', name: '西瓜', keywords: ['绿', '水果', 'watermelon'] },
  { emoji: '🍑', name: '桃子', keywords: ['粉', '水果', 'peach'] },
  { emoji: '🍒', name: '樱桃', keywords: ['红', '水果', 'cherry'] },
  { emoji: '🥝', name: '猕猴桃', keywords: ['绿', '水果', 'kiwi'] },
  { emoji: '🍓', name: '草莓', keywords: ['红', '水果', 'strawberry'] },
  { emoji: '🥭', name: '芒果', keywords: ['黄', '水果', 'mango'] },
  { emoji: '🍍', name: '菠萝', keywords: ['黄', '水果', 'pineapple'] },
  { emoji: '🥥', name: '椰子', keywords: ['棕', '水果', 'coconut'] },
  { emoji: '🥑', name: '牛油果', keywords: ['绿', '水果', 'avocado'] },
  { emoji: '🫘', name: '豆子', keywords: ['豆', 'bean'] },
  { emoji: '🥕', name: '胡萝卜', keywords: ['橙', '蔬菜', 'carrot'] },
  { emoji: '🧅', name: '洋葱', keywords: ['紫', '蔬菜', 'onion'] },
  { emoji: '🥬', name: '蔬菜', keywords: ['绿', '叶', 'vegetable'] },
  { emoji: '🍞', name: '面包', keywords: ['烤', 'bread'] },
  { emoji: '🍔', name: '汉堡', keywords: ['快餐', 'burger'] },
  { emoji: '🧀', name: '奶酪', keywords: ['芝士', 'cheese'] },
  { emoji: '🥚', name: '鸡蛋', keywords: ['蛋', 'egg'] },
  { emoji: '🍽️', name: '餐具', keywords: ['吃', '餐', 'dining'] },

  // 🐱 动物
  { emoji: '🐱', name: '猫', keywords: ['喵', 'cat'] },
  { emoji: '🐶', name: '狗', keywords: ['汪', 'dog'] },
  { emoji: '🐘', name: '大象', keywords: ['象', 'elephant'] },
  { emoji: '🐸', name: '青蛙', keywords: ['呱', 'frog'] },
  { emoji: '🐐', name: '山羊', keywords: ['羊', 'goat'] },
  { emoji: '🐴', name: '马', keywords: ['horse'] },
  { emoji: '🐒', name: '猴子', keywords: ['猴', 'monkey'] },
  { emoji: '🦉', name: '猫头鹰', keywords: ['鸟', '夜', 'owl'] },
  { emoji: '🐧', name: '企鹅', keywords: ['鸟', '冰', 'penguin'] },
  { emoji: '🐰', name: '兔子', keywords: ['兔', 'rabbit'] },
  { emoji: '🐍', name: '蛇', keywords: ['长', 'snake'] },
  { emoji: '🐯', name: '老虎', keywords: ['虎', 'tiger'] },
  { emoji: '🦄', name: '独角兽', keywords: ['马', '角', 'unicorn'] },
  { emoji: '🐋', name: '鲸鱼', keywords: ['海', 'whale'] },
  { emoji: '🐺', name: '狼', keywords: ['月', 'wolf'] },
  { emoji: '🦓', name: '斑马', keywords: ['条纹', 'zebra'] },
  { emoji: '🦘', name: '袋鼠', keywords: ['跳', 'kangaroo'] },
  { emoji: '🐑', name: '绵羊', keywords: ['毛', 'sheep'] },
  { emoji: '🦅', name: '鹰', keywords: ['鸟', '飞', 'eagle'] },
  { emoji: '🐬', name: '海豚', keywords: ['海', '跳', 'dolphin'] },
  { emoji: '🦆', name: '鸭子', keywords: ['水', 'duck'] },
  { emoji: '🦋', name: '蝴蝶', keywords: ['飞', '美', 'butterfly'] },
  { emoji: '🐌', name: '蜗牛', keywords: ['慢', '壳', 'snail'] },
  { emoji: '🦊', name: '狐狸', keywords: ['聪明', 'fox'] },
  { emoji: '🐨', name: '考拉', keywords: ['树', 'koala'] },
  { emoji: '🐂', name: '牛', keywords: ['牦牛', 'bull'] },
  { emoji: '🦁', name: '狮子', keywords: ['王', 'lion'] },

  // 🌸 自然植物
  { emoji: '🌸', name: '樱花', keywords: ['粉', '花', 'cherry blossom'] },
  { emoji: '🌹', name: '玫瑰', keywords: ['红', '花', 'rose'] },
  { emoji: '🌻', name: '向日葵', keywords: ['黄', '花', 'sunflower'] },
  { emoji: '🍃', name: '叶子', keywords: ['绿', '叶', 'leaf'] },
  { emoji: '🌾', name: '小麦', keywords: ['稻', '麦', 'wheat'] },
  { emoji: '🌳', name: '树', keywords: ['森林', 'tree'] },
  { emoji: '🌵', name: '仙人掌', keywords: ['沙漠', 'cactus'] },
  { emoji: '🌴', name: '棕榈树', keywords: ['热带', 'palm'] },

  // ☀️ 天气自然
  { emoji: '☀️', name: '太阳', keywords: ['晴', '光', 'sun'] },
  { emoji: '🌙', name: '月亮', keywords: ['夜', '弯', 'moon'] },
  { emoji: '⭐', name: '星星', keywords: ['亮', 'star'] },
  { emoji: '🌈', name: '彩虹', keywords: ['雨后', '七色', 'rainbow'] },
  { emoji: '☁️', name: '云', keywords: ['天', 'cloud'] },
  { emoji: '🌧️', name: '雨', keywords: ['下雨', 'rain'] },
  { emoji: '❄️', name: '雪花', keywords: ['冰', '冬', 'snow'] },
  { emoji: '⚡', name: '闪电', keywords: ['雷', '电', 'lightning'] },
  { emoji: '🔥', name: '火', keywords: ['热', '烧', 'fire'] },
  { emoji: '💧', name: '水滴', keywords: ['水', 'drop'] },
  { emoji: '🌊', name: '海浪', keywords: ['海', '波', 'wave'] },
  { emoji: '🌋', name: '火山', keywords: ['喷发', 'volcano'] },
  { emoji: '⛰️', name: '山', keywords: ['高', 'mountain'] },
  { emoji: '🌌', name: '银河', keywords: ['宇宙', '星', 'galaxy'] },

  // ❤️ 符号表情
  { emoji: '❤️', name: '红心', keywords: ['爱', '心', 'heart'] },
  { emoji: '💛', name: '黄心', keywords: ['爱', '心'] },
  { emoji: '💚', name: '绿心', keywords: ['爱', '心'] },
  { emoji: '💙', name: '蓝心', keywords: ['爱', '心'] },
  { emoji: '💜', name: '紫心', keywords: ['爱', '心'] },
  { emoji: '🧡', name: '橙心', keywords: ['爱', '心'] },
  { emoji: '💔', name: '心碎', keywords: ['伤', 'broken'] },
  { emoji: '❓', name: '问号', keywords: ['问题', '疑问', 'question'] },
  { emoji: '❌', name: '叉号', keywords: ['错', '否', 'cross'] },
  { emoji: '✅', name: '对号', keywords: ['对', '是', 'check'] },
  { emoji: '💯', name: '满分', keywords: ['百', 'perfect'] },
  { emoji: '⭕', name: '圆圈', keywords: ['圆', 'circle'] },
  { emoji: '👑', name: '王冠', keywords: ['国王', '女王', 'crown'] },
  { emoji: '💎', name: '钻石', keywords: ['宝石', 'diamond'] },
  { emoji: '🔑', name: '钥匙', keywords: ['开', 'key'] },
  { emoji: '🔔', name: '铃铛', keywords: ['响', 'bell'] },
  { emoji: '🎶', name: '音符', keywords: ['歌', 'music'] },
  { emoji: '🎵', name: '音乐', keywords: ['歌', 'song'] },

  // 🏠 建筑
  { emoji: '🏠', name: '房子', keywords: ['家', 'house'] },
  { emoji: '⛪', name: '教堂', keywords: ['church'] },
  { emoji: '🏰', name: '城堡', keywords: ['王', 'castle'] },
  { emoji: '🎪', name: '帐篷', keywords: ['马戏', 'circus'] },

  // 🚗 交通
  { emoji: '🚗', name: '汽车', keywords: ['车', 'car'] },
  { emoji: '🚂', name: '火车', keywords: ['铁', 'train'] },
  { emoji: '✈️', name: '飞机', keywords: ['飞', 'airplane'] },
  { emoji: '🚀', name: '火箭', keywords: ['太空', 'rocket'] },
  { emoji: '🚢', name: '轮船', keywords: ['海', 'ship'] },
  { emoji: '🚲', name: '自行车', keywords: ['骑车', 'bicycle'] },

  // 🎸 乐器艺术
  { emoji: '🎸', name: '吉他', keywords: ['弹', 'guitar'] },
  { emoji: '🎹', name: '钢琴', keywords: ['弹', 'piano'] },
  { emoji: '🎻', name: '小提琴', keywords: ['拉', 'violin'] },
  { emoji: '🥁', name: '鼓', keywords: ['敲', 'drum'] },
  { emoji: '🎺', name: '喇叭', keywords: ['吹', 'trumpet'] },
  { emoji: '🎨', name: '调色板', keywords: ['画', 'art', 'paint'] },
  { emoji: '📷', name: '相机', keywords: ['照片', 'camera'] },

  // ⚽ 运动
  { emoji: '⚽', name: '足球', keywords: ['踢', 'soccer'] },
  { emoji: '🏀', name: '篮球', keywords: ['投', 'basketball'] },
  { emoji: '🎾', name: '网球', keywords: ['打', 'tennis'] },
  { emoji: '🏓', name: '乒乓球', keywords: ['打', 'pingpong'] },
  { emoji: '🏊', name: '游泳', keywords: ['水', 'swim'] },
  { emoji: '⛷️', name: '滑雪', keywords: ['雪', 'ski'] },

  // 👤 人物身体
  { emoji: '👁️', name: '眼睛', keywords: ['看', 'eye'] },
  { emoji: '👄', name: '嘴巴', keywords: ['说', 'mouth'] },
  { emoji: '🦶', name: '脚', keywords: ['走', 'foot'] },
  { emoji: '👍', name: '赞', keywords: ['好', '拇指', 'thumbsup'] },
  { emoji: '👎', name: '踩', keywords: ['差', 'thumbsdown'] },
  { emoji: '👏', name: '鼓掌', keywords: ['拍手', 'clap'] },
  { emoji: '🤝', name: '握手', keywords: ['合作', 'handshake'] },
  { emoji: '🤔', name: '思考', keywords: ['想', 'think'] },
  { emoji: '😊', name: '微笑', keywords: ['笑', 'happy'] },
  { emoji: '😢', name: '哭泣', keywords: ['哭', 'sad'] },
  { emoji: '😱', name: '惊恐', keywords: ['怕', 'scream'] },
  { emoji: '🤗', name: '拥抱', keywords: ['抱', 'hug'] },
  { emoji: '💪', name: '肌肉', keywords: ['强', '力量', 'muscle'] },

  // 🎯 物品
  { emoji: '🪑', name: '椅子', keywords: ['坐', 'chair'] },
  { emoji: '🚪', name: '门', keywords: ['开', 'door'] },
  { emoji: '🎩', name: '礼帽', keywords: ['帽', 'hat'] },
  { emoji: '👟', name: '运动鞋', keywords: ['鞋', 'shoe'] },
  { emoji: '📱', name: '手机', keywords: ['电话', 'phone'] },
  { emoji: '💡', name: '灯泡', keywords: ['主意', '亮', 'idea'] },
  { emoji: '🔦', name: '手电筒', keywords: ['灯', 'lamp'] },
  { emoji: '🧊', name: '冰块', keywords: ['冷', 'ice'] },
  { emoji: '☂️', name: '雨伞', keywords: ['伞', 'umbrella'] },
  { emoji: '🪁', name: '风筝', keywords: ['飞', 'kite'] },
  { emoji: '🧶', name: '毛线', keywords: ['织', 'yarn'] },
  { emoji: '🪀', name: '溜溜球', keywords: ['玩', 'yoyo'] },
  { emoji: '🪓', name: '斧头', keywords: ['砍', 'axe'] },
  { emoji: '⚓', name: '锚', keywords: ['船', 'anchor'] },
  { emoji: '🧦', name: '袜子', keywords: ['穿', 'sock'] },
  { emoji: '🛏️', name: '床', keywords: ['睡', 'bed'] },
  { emoji: '📦', name: '箱子', keywords: ['盒', 'box'] },
  { emoji: '🪺', name: '鸟巢', keywords: ['巢', 'nest'] },
  { emoji: '☠️', name: '骷髅', keywords: ['死', 'skull'] },
  { emoji: '🪼', name: '水母', keywords: ['海', 'jellyfish'] },
  { emoji: '🫙', name: '罐子', keywords: ['瓶', 'jar'] },
  { emoji: '👔', name: '领带', keywords: ['衣', 'tie'] },
  { emoji: '👓', name: '眼镜', keywords: ['看', 'glasses'] },
  { emoji: '🎒', name: '书包', keywords: ['背', 'bag'] },
  { emoji: '🧲', name: '磁铁', keywords: ['吸', 'magnet'] },
  { emoji: '🔮', name: '水晶球', keywords: ['算命', 'crystal'] },
  { emoji: '🪄', name: '魔法棒', keywords: ['魔', 'wand'] },
  { emoji: '🏅', name: '奖牌', keywords: ['赢', 'medal'] },
  { emoji: '🏆', name: '奖杯', keywords: ['赢', 'trophy'] },
  { emoji: '🎡', name: '摩天轮', keywords: ['转', 'wheel'] },
  { emoji: '🎢', name: '过山车', keywords: ['刺激', 'coaster'] },
  { emoji: '🕐', name: '时钟', keywords: ['时间', 'clock'] },
  { emoji: '⏰', name: '闹钟', keywords: ['响', 'alarm'] },
  { emoji: '🗺️', name: '地图', keywords: ['路', 'map'] },
  { emoji: '🧭', name: '指南针', keywords: ['方向', 'compass'] },
  { emoji: '🏳️', name: '白旗', keywords: ['旗', 'flag'] },
  { emoji: '🤴', name: '王子', keywords: ['王', 'prince'] },
  { emoji: '👸', name: '公主', keywords: ['王', 'princess'] },
  { emoji: '🧙', name: '巫师', keywords: ['魔', 'wizard'] },
  { emoji: '🧛', name: '吸血鬼', keywords: ['暗', 'vampire'] },
  { emoji: '👻', name: '幽灵', keywords: ['鬼', 'ghost'] },
  { emoji: '🤖', name: '机器人', keywords: ['机', 'robot'] },
  { emoji: '👽', name: '外星人', keywords: ['星', 'alien'] },
  { emoji: '🎭', name: '面具', keywords: ['戏', 'mask'] },
  { emoji: '🎪', name: '马戏团', keywords: ['表演', 'circus'] },

  // 🏳️ 标志
  { emoji: '🇨🇳', name: '中国', keywords: ['国旗', 'china'] },
  { emoji: '🇺🇸', name: '美国', keywords: ['国旗', 'usa'] },
  { emoji: '🇬🇧', name: '英国', keywords: ['国旗', 'uk'] },
  { emoji: '🌍', name: '地球', keywords: ['世界', 'earth'] },
];
